Repository iNESlab/Golbang_BE, pull requests merged in 2024-11, with the labels that each got.

#66 Feat: 관리자 계정 자동화 스크립트 추가 및 EC2 IP를 장고 호스트 허용 등록
  Dockerfile
  Dockerfile.prod
  accounts/models.py
  create-superuser.py
  golbang/settings.py
Labels: ✨Feat

#67 Feat: FCM 알림 기능 구현 & Golf Course 조회 API 구현
  .gitignore
  accounts/views.py
  clubs/tasks.py
  clubs/views/club_common.py
  docker-compose.yml
  events/serializers.py
  events/tasks.py
  events/test.py
  events/views/views.py
  golbang/settings.py
  golbang/urls.py
  golf_data/__init__.py
  golf_data/admin.py
  golf_data/apps.py
  golf_data/data_import.py
  golf_data/migrations/0001_initial.py
  golf_data/migrations/0002_excelfileupload.py
  golf_data/migrations/__init__.py
  golf_data/models.py
  golf_data/serializers.py
  golf_data/tests.py
  golf_data/urls.py
  golf_data/views.py
  push_notification/__init__.py
  push_notification/admin.py
  push_notification/models.py
  push_notification/push_fcm_notification.py
  push_notification/views.py
  requirements.txt
  send_fcm_test.py
  utils/delete_s3_image.py
  utils/push_fcm_notification.py
Labels: ✨Feat

#69 Hotfix: #55-feat: 설정파일에 FCM 관련 패키지 추가
  golbang/settings.py
Labels: 🐛 Bug

#71 Feat: 이벤트/모임/알림 기능 관련하여 프론트엔드 요청사항 반영
  clubs/tasks.py
  docker-compose.yml
  events/serializers.py
  events/tasks.py
  utils/push_fcm_notification.py
Labels: ✨Feat

#73 Hotfix: FCM - serviceAccountKey 재발급 & Feat: 알림 내역 관련 API 추가
  .github/workflows/main.yml
  .gitignore
  golbang/settings.py
  golbang/urls.py
  notifications/__init__.py
  notifications/admin.py
  notifications/apps.py
  notifications/migrations/__init__.py
  notifications/models.py
  notifications/redis_interface.py
  notifications/tests.py
  notifications/urls.py
  notifications/views/__init__.py
  notifications/views/notification_views.py
  send_fcm_test.py
  utils/push_fcm_notification.py
Labels: ✨Feat

#74 Feat: 알림 조회 API 구현
  clubs/tasks.py
  events/tasks.py
  notifications/redis_interface.py
  notifications/views/notification_views.py
Labels: ✨Feat

#75 Hotfix: 모임 생성 후 안내 메시지 추가 & UserInfo 함수에 try-except 로그 추가
  accounts/views.py
  clubs/tasks.py
Labels: 🐛 Bug, ✨Feat

#77 Feat: 모임 조회 시 요청한 사용자가 관리자인지 여부도 함께 반환
  clubs/serializers.py
Labels: ✨Feat
