Repository iNESlab/Golbang_BE, pull requests merged in 2024-12, with the labels that each got.

#78 Hotfix: Golf_course 엑셀파일의 Tees 시트가 제대로 데이터베이스에 저장되지 않는 문제 해결
  golf_data/data_import.py
Labels: 🔨 Fix

#79 Hotfix: 누락된 홀 점수를 0으로 채워 18홀 점수를 반환하도록 로직 수정
  participants/models.py
Labels: ✨Feat

#82 Feat&Deploy: 회원탈퇴 및 비밀번호 변경 API구현 & 배포 및 빌드 최적화
  .dockerignore
  .github/workflows/main.yml
  accounts/urls.py
  accounts/views.py
  clubs/views/club_member.py
  docker-compose.moon.yml
  golbang/settings.py
Labels: ✨Feat, 🚀Build

#86 Feat: 알림 내역 저장 시간 연장, 알림 저장 시 event_id, club_id 함께 저장, celery beat 작업 수정
  clubs/tasks.py
  events/tasks.py
  golbang/settings.py
  notifications/redis_interface.py
Labels: ✨Feat

#87 hotfix: 참가자 정보 레디스 정보를 읽어올 때, 키값에서 누락된 이벤트 id 추가
  participants/stroke/mysql_interface.py
  participants/stroke/stroke_group_consumers.py
Labels: 🔨 Fix

#90 Feat: 피드백 API 구현
  feedbacks/__init__.py
  feedbacks/admin.py
  feedbacks/apps.py
  feedbacks/migrations/0001_initial.py
  feedbacks/migrations/0002_alter_feedback_created_at_alter_feedback_message.py
  feedbacks/migrations/__init__.py
  feedbacks/models.py
  feedbacks/serializers.py
  feedbacks/urls.py
  feedbacks/views.py
  golbang/settings.py
  golbang/urls.py
Labels: ✨Feat
