Repository iNESlab/Golbang_BE, pull requests merged in 2024-08, with the labels that each got.

#24 Feat&Comment: 참가자 중복 검사 및 주석 추가
  .cz.toml
  .github/workflows/.github/workflows/bump-version.yml
  .github/workflows/ci-cd.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  accounts/migrations/0005_alter_user_handicap.py
  accounts/models.py
  docker-compose.yml
  events/models.py
  events/serializers.py
  events/urls.py
  events/utils.py
  events/views/__init__.py
  events/views/handicap_match_views.py
  events/views/views.py
  media/clubs/emoji_introduce.png
  media/clubs/emoji_notebook.png
  media/clubs/emoji_notebook_674OvKk.png
  media/clubs/emoji_notebook_rHNGQ6d.png
  participants/admin.py
  participants/migrations/0003_holescore.py
  participants/migrations/0004_remove_holescore_event.py
  participants/models.py
  participants/serializers.py
  participants/urls.py
  participants/views.py
  requirements.txt
  utils/error_handlers.py
Labels: 🐛 Bug, ✨Feat

#29 Feat: 웹소켓 스코어 기록/조회 기능 개발
  Dockerfile
  auth/jwt_auth_middleware.py
  docker-compose.moon.yml
  golbang/asgi.py
  golbang/settings.py
  participants/models.py
  participants/routing.py
  participants/serializers.py
  participants/socket/__init__.py
  participants/socket/event_consumers.py
  participants/socket/group_consumers.py
  requirements.txt
Labels: 🐛 Bug, ✨Feat

#33 Feat: 웹소켓 스코어 기록/조회 기능 개발 2
  Dockerfile
  events/models.py
  participants/models.py
  participants/routing.py
  participants/socket/__init__.py
  participants/socket/event_consumers.py
  participants/socket/group_consumers.py
  participants/stroke/data_class.py
  participants/stroke/mysql_interface.py
  participants/stroke/redis_interface.py
  participants/stroke/stroke_event_consumers.py
  participants/stroke/stroke_group_consumers.py
Labels: ✨Feat, 🔨 Fix

#25 CI/CD: Docker 기반 배포 파이프라인 구성
  .github/workflows/CICD.yml
  .github/workflows/bump-version.yml
  .github/workflows/ci-cd.yml
  .gitignore
  .pre-commit-config.yaml
  Dockerfile
  Dockerfile.prod
  config/docker/entrypoint.prod.sh
  config/nginx/Dockerfile
  config/nginx/nginx.conf
  docker-compose.prod.yml
  docker-compose.yml
  golbang/settings.py
  golbang/settings/__init__.py
  golbang/settings/base.py
  golbang/settings/dev.py
  golbang/settings/prod.py
  media/clubs/emoji_introduce.png
  media/clubs/emoji_notebook.png
  media/clubs/emoji_notebook_674OvKk.png
  media/clubs/emoji_notebook_rHNGQ6d.png
  requirements.txt
Labels: ✨Feat, 🚀Build

#37 Feat & Fix: 이벤트 결과(전체 결과 조회, 스코어카드 결과 조회), 회원정보(목록, 조회, 수정, 비밀번호)
  .gitignore
  accounts/migrations/0006_user_profile_image.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  auth/api.py
  docker-compose.yml
  events/migrations/0003_event_group_win_team_event_group_win_team_handicap_and_more.py
  events/models.py
  events/serializers.py
  events/utils.py
  events/views/views.py
  golbang/settings.py
  participants/migrations/0005_participant_handicap_score.py
  participants/migrations/0006_alter_participant_rank.py
  participants/migrations/0007_participant_is_group_win_and_more.py
  participants/migrations/0008_participant_handicap_rank.py
  participants/models.py
  participants/routing.py
  participants/serializers.py
  participants/stroke/data_class.py
  participants/stroke/mysql_interface.py
  participants/stroke/redis_interface.py
  participants/stroke/stroke_event_consumers.py
  participants/stroke/stroke_group_consumers.py
  participants/urls.py
  participants/views.py
  requirements.txt
Labels: 🐛 Bug, ✨Feat

#38 Feat: 이벤트 결과(전체 결과 조회, 스코어카드 결과 조회)에 팀전 추가
  events/migrations/0004_event_team_a_group_wins_and_more.py
  events/models.py
  events/serializers.py
  events/views/views.py
  participants/models.py
Labels: ✨Feat

#39 Feat: 통계 - 개인통계(Overall, Yearly, Period), 모임별 랭킹 (Club-specific Ranks and Events)
  accounts/serializers.py
  accounts/views.py
  auth/api.py
  celerybeat-schedule
  clubs/migrations/0003_clubmember_total_handicap_rank_and_more.py
  clubs/migrations/0004_remove_clubmember_total_handicap_rank_and_more.py
  clubs/migrations/0005_clubmember_total_handicap_rank_and_more.py
  clubs/migrations/0006_clubmember_total_handicap_score_and_more.py
  clubs/migrations/0007_rename_total_sum_score_clubmember_total_avg_score_and_more.py
  clubs/migrations/0008_alter_clubmember_total_avg_score_and_more.py
  clubs/models.py
  clubs/serializers.py
  clubs/tasks.py
  clubs/urls.py
  clubs/utils.py
  clubs/views/club_statistics.py
  docker-compose.yml
  events/migrations/0005_alter_event_club.py
  events/models.py
  events/serializers.py
  events/views/views.py
  golbang/__init__.py
  golbang/celery.py
  golbang/settings.py
  golbang/urls.py
  participants/migrations/0009_participant_points.py
  participants/migrations/0010_remove_participant_points.py
  participants/migrations/0011_participant_points.py
  participants/models.py
  participants/serializers.py
  participants/stroke/data_class.py
  participants/stroke/mysql_interface.py
  participants/tests.py
  participants/urls.py
  participants/utils/statistics.py
  participants/views/__init__.py
  participants/views/participants_view.py
  participants/views/statistics_view.py
  requirements.txt
Labels: ✨Feat

#41 fix: 모임 내 멤버 리스트 시리얼라이저와 모임별 랭킹 조회 시리얼라이저 수정
  clubs/serializers.py
  events/serializers.py
Labels: 🐛 Bug

#42 hotfix: event 조회시 my_participant_id 추가
  events/serializers.py
  events/views/views.py
Labels: 🔨 Fix
