Repository iNESlab/Golbang_BE, pull requests merged in 2024-09, with the labels that each got.

#44 hotfix(participants): ParticipantDetailSerializer 수정
  celerybeat-schedule
  participants/serializers.py
Labels: 🔨 Fix

#45 Refactor: 소켓 응답시 사용자 이름 추가 및 data class post_init 구조 통일
  participants/stroke/data_class.py
  participants/stroke/redis_interface.py
  participants/stroke/stroke_group_consumers.py
Labels: 🔨 Fix

#47 Feat: ClubProfile 시리얼라이저 생성 및 Event 상세 조회시 ClubProfile 정보 반환
  clubs/serializers.py
  events/serializers.py
Labels: ✨Feat

#48 Hotfix(accounts): 회원정보 시리얼라이저와 뷰 수정
  accounts/migrations/0007_alter_user_handicap.py
  accounts/models.py
  accounts/serializers.py
  accounts/views.py
  celerybeat-schedule
Labels: refactoring

#49 Fix: 유저가 속한 조를 반환하지 않던 로직 변경
  events/serializers.py
Labels: 🔨 Fix

#50 Minjeong / Fix: 모임 관련 로직 수정
  accounts/serializers.py
  accounts/views.py
  celerybeat-schedule
  clubs/views/club_common.py
Labels: ✨Feat, 🔨 Fix

#52 Fix: 이미지 삭제 시 S3 버킷에도 삭제 되도록 수정
  accounts/views.py
  celerybeat-schedule
  utils/delete_s3_image.py
Labels: 🔨 Fix

#53 Feat: 이벤트 랭킹 조회시 0점 참가자는 제외해서 응답
  participants/stroke/redis_interface.py
  participants/stroke/stroke_event_consumers.py
Labels: ✨Feat
