Repository iNESlab/Golbang_BE, pull requests merged in 2025-04, with the labels that each got.

#158 Refactor: 참가자 캐싱 및 자동 동기화
  events/serializers.py
  golbang/settings.py
  participants/stroke/data_class.py
  participants/stroke/mysql_interface.py
  participants/stroke/redis_interface.py
  participants/stroke/stroke_event_consumers.py
  participants/stroke/stroke_group_consumers.py
  participants/tasks.py
Labels: ✨Feat, 🔨 Fix

#159 hotfix: 점수 합계 변경이 안되던 버그 및 프론트에 int가 아닌 string으로 보내던 버그 수정
  participants/stroke/data_class.py
  participants/stroke/redis_interface.py
  participants/stroke/stroke_event_consumers.py
  participants/stroke/stroke_group_consumers.py
  participants/tasks.py
Labels: ✨Feat, 🔨 Fix

#163 bug: redis -> mysql 동기화시 합계, 랭크 변경 안됨
  participants/stroke/data_class.py
  participants/tasks.py
Labels: 🐛 Bug

#164 hotfix: mysql 랭크에 null이 저장되는 버그
  participants/tasks.py
Labels: 🐛 Bug, 🔨 Fix

#165 hotfix: 기존에 잘못 동기화된 랭크 버그
  participants/stroke/data_class.py
Labels: 🔨 Fix

#167 bug: celery에 task 로그가 안찍힘
  golbang/celery.py
  participants/stroke/redis_interface.py
Labels: 🐛 Bug

#169 Feat: 스코어카드 조회 시 빈 값 Null 반환 및 Redis Null 키 삭제 로직 추가
  participants/models.py
  participants/stroke/redis_interface.py
  participants/stroke/stroke_group_consumers.py
Labels: ✨Feat

#170 Feat: 그룹별 홀 확인/수정 기능 및 Redis 상태 관리 로직 구현
  participants/stroke/redis_interface.py
  participants/stroke/stroke_group_consumers.py
Labels: ✨Feat, 🔨 Fix

#171 Fix: 홀 확인/수정 시 같은 조원에게도 스코어 업데이트 브로드캐스트
  participants/stroke/stroke_group_consumers.py
Labels: 🔨 Fix
