Repository iNESlab/Golbang_BE, pull requests merged in 2025-01, with the labels that each got.

#91 hotfix: 모임 나가기 api return 누락 추가
  clubs/views/club_member.py
Labels: 🔨 Fix

#92 fix: 랭킹 웹소켓에서 유저 프로필 이미지 반환하도록 추가
  participants/stroke/stroke_event_consumers.py
Labels: 🔨 Fix

#93 hotfix: 모델 Image타입은 json 직렬이 안됨. url을 추출해서 넣어야함
  participants/stroke/stroke_event_consumers.py
Labels: 🔨 Fix

#94 fix&deploy: 스코어 카드 참가자는 참가 수락한 인원들만 반환함+배포용 스크립트 작업
  .github/workflows/main.yml
  docker-compose.prod.yml
  participants/stroke/mysql_interface.py
Labels: 🔨 Fix

#95 Hotfix: sympy패키지를 requirements 파일에 추가
  requirements.txt
Labels: 🔨 Fix

#98 hotfix: redis_client에 password 추가
  participants/stroke/redis_interface.py
Labels: 🔨 Fix

#99 hotfix: CHANNEL_LAYER에 레디스 비밀번호 입력 방식 변경
  golbang/settings.py
Labels: 🔨 Fix

#103 Hotfix: CICD 파이프라인에 release 관련 코드 추가
  .github/workflows/main.yml
  .gitignore
Labels: 🚀Build

#104 Hotfix: PROD 용 S3와 RDS 생성 후 github secret 변수명 변경 적용
  .github/workflows/main.yml
Labels: 🚀Build

#105 Hotfix: PROD 용 S3와 RDS 생성 후 github secret 변수명 변경 적용 -> RELEASE 통합
  .github/workflows/main.yml
Labels: 🚀Build

#107 hotfix: 개발 서버 runner label 변경
  .github/workflows/main.yml
Labels: 🔨 Fix

#109 feat: CSRF 오류 해결 및 CORS 화이트리스트 도메인 추가
  golbang/settings.py
Labels: ✨Feat, 🔨 Fix

#110 RELEASE 용 테스트
  golbang/settings.py
Labels: 🚀Build

#112 hotfix: http -> https 리다이렉트 해제
  golbang/settings.py
Labels: 🔨 Fix

#113 fix: CSRF 리다이렉트된 경우 추가
  golbang/settings.py
Labels: 🔨 Fix

#114 release test
  golbang/settings.py
Labels: 🚀Build

#115 hotfix: 웹소켓 통신시, Allowed 에러발생하여 ALB 도메인 추가
  golbang/settings.py
Labels: 🔨 Fix

#116 hotfix: wss로 업그레이드
  participants/routing.py
Labels: 🔨 Fix

#117 Release: wss 업그레이드 배포
  golbang/settings.py
  participants/routing.py
Labels: ✨Feat, 🔨 Fix, 🚀Build
