Repository iNESlab/Golbang_BE, pull requests merged in 2025-03, with the labels that each got.

#125 Release: 유저 초대를 위한 API request, 시리얼라이저 수정 사항 배포
  clubs/serializers.py
  clubs/views/club_admin.py
Labels: ✨Feat, 🚀Build

#124 docs: 리팩토링해야 할 TODO 및 주석 추가
  accounts/admin.py
  accounts/serializers.py
  accounts/views.py
  auth/api.py
  auth/authenticate.py
  auth/jwt_auth_middleware.py
  celerybeat-schedule
  clubs/models.py
  clubs/serializers.py
  clubs/views/club_common.py
  participants/stroke/stroke_event_consumers.py
Labels: 📄 Docs

#126 Feat&Fix: 골프장 코스 정보 데이터 구조 개선 & 이벤트 조회 시 골프장 및 코스 정보 반영
  events/serializers.py
  golbang/settings.py
  golf_data/data_import.py
  golf_data/migrations/0001_initial.py
  golf_data/migrations/0002_alter_golfclub_latitude_alter_golfclub_longitude.py
  golf_data/migrations/0002_excelfileupload.py
  golf_data/models.py
  golf_data/serializers.py
  golf_data/views.py
Labels: ✨Feat, 🔨 Fix

#127 Fix(dockerfile): 서버 마이그레이션 에러를 해결하기 위한 디버깅용 명령어 추가
  Dockerfile.prod
Labels: 🐛 Bug, 🚀Build

#128 Fix: migrations 파일 재생성
  Dockerfile.prod
  golf_data/migrations/0001_initial.py
  golf_data/migrations/0002_alter_golfclub_latitude_alter_golfclub_longitude.py
Labels: 🐛 Bug, 🚀Build

#129 Release: 골프장 코스 정보 데이터 구조 개선 & 이벤트 조회 시 골프장 및 코스 정보 반영
  accounts/admin.py
  accounts/serializers.py
  accounts/views.py
  auth/api.py
  auth/authenticate.py
  auth/jwt_auth_middleware.py
  celerybeat-schedule
  clubs/models.py
  clubs/serializers.py
  clubs/views/club_common.py
  events/serializers.py
  golbang/settings.py
  golf_data/data_import.py
  golf_data/migrations/0001_initial.py
  golf_data/migrations/0002_excelfileupload.py
  golf_data/models.py
  golf_data/serializers.py
  golf_data/views.py
  participants/stroke/stroke_event_consumers.py
Labels: 🚀Build

#130 fix(golf_data): Data too long for column 'hole_11_handicap' 에러 해결
  golf_data/migrations/0002_alter_tee_hole_10_handicap_alter_tee_hole_10_par_and_more.py
  golf_data/models.py
Labels: 🐛 Bug, 🔨 Fix

#131 Release: Data too long for column 'hole_11_handicap' 에러 해결
  golf_data/migrations/0002_alter_tee_hole_10_handicap_alter_tee_hole_10_par_and_more.py
  golf_data/models.py
Labels: 🚀Build

#134 [Release] 액세스/리프레시 토큰 기한 연장 + DB마이그레이션 해결
  auth/api.py
  golbang/settings.py
Labels: 🚀Build

#135 Feat: 이미지 업로드 최적화 - WebP 변환 및 용량 압축 적용
  accounts/views.py
  clubs/views/club_common.py
  golf_data/admin.py
  utils/compress_image.py
  utils/delete_s3_image.py
Labels: ✨Feat, 📄 Docs

#136 [Release] 이미지 압축 및 webp 변환
  accounts/views.py
  clubs/views/club_common.py
  golf_data/admin.py
  utils/compress_image.py
  utils/delete_s3_image.py
Labels: 🚀Build

#137 feat(event): 이벤트 스코어 카드 조회 시 참석/참석회식 을 선택한 참여자들만 반환되도록 필터링 추가
  events/views/views.py
Labels: ✨Feat

#138 Fix(Event): 이벤트 수정 시 참여자 업데이트 로직 개선(기존 참여자 데이터 부분 업데이트)
  events/serializers.py
  events/tasks.py
Labels: ✨Feat, 🔨 Fix

#139 Release: (iOS 1.0.6) - 이벤트 스코어카드 조회 시 참석여부 필터링, 이벤트 수정 시 참여자 업데이트 개선
  events/serializers.py
  events/tasks.py
  events/views/views.py
Labels: 🚀Build

#140 Feat(Club): 모임 관리자의 모임 수정 API 기능 보완(엔드포인트 변경/이미지 변경 기능&관리자 변경 기능 추가)
  clubs/urls.py
  clubs/views/club_admin.py
  clubs/views/club_member.py
Labels: ✨Feat, 🔨 Fix

#141 Release: (iOS 1.0.8) 모임 관리자의 모임 수정 API 기능 보완(엔드포인트 변경/이미지 변경 기능&관리자 변경 기능 추가)
  clubs/urls.py
  clubs/views/club_admin.py
  clubs/views/club_member.py
Labels: 🚀Build

#142 fix(clubs): 모임 수정 시 유저 아이디를 기반으로 처리하는 것이 아닌 ClubMember 아이디를 기반으로 처리하도록 수정
  clubs/views/club_admin.py
Labels: 🔨 Fix

#143 Release: (iOS 1.0.8+1, Android 1.0.0+39) 모임 수정 API request 수정
  clubs/views/club_admin.py
Labels: 🚀Build

#144 fix(clubs): 모임 멤버 강제 삭제 시 User pk가 아닌 Clubmember pk로 처리되도록 수정
  clubs/views/club_admin.py
Labels: 🐛 Bug, 🔨 Fix

#145 refactor: 멤버 초대 응답 수정
  clubs/views/club_admin.py
Labels: refactoring

#146 fix(clubs): bulk_create 후 pk 미반환 문제 해결
  clubs/views/club_admin.py
Labels: 🔨 Fix

#148 Bugfix: 중첩 Response 반환 문제 수정 및 통계 계산 로직 분리
  clubs/views/club_admin.py
  golf_data/views.py
  participants/utils/statistics.py
  participants/views/statistics_view.py
Labels: 🔨 Fix

#150 Feat: 신페리오 핸디캡 계산 기능 및 UI 통합
  calculator/__init__.py
  calculator/admin.py
  calculator/apps.py
  calculator/migrations/__init__.py
  calculator/models.py
  calculator/prompting.py
  calculator/serializers.py
  calculator/templates/calculator/upload_form.html
  calculator/tests.py
  calculator/urls.py
  calculator/views.py
  golbang/settings.py
  golbang/urls.py
  utils/tempfile_helpers.py
Labels: ✨Feat

#151 Release - 신페리오 핸디캡 계산 기능 및 UI 통합
  calculator/__init__.py
  calculator/admin.py
  calculator/apps.py
  calculator/migrations/__init__.py
  calculator/models.py
  calculator/prompting.py
  calculator/serializers.py
  calculator/templates/calculator/upload_form.html
  calculator/tests.py
  calculator/urls.py
  calculator/views.py
  golbang/settings.py
  golbang/urls.py
  utils/tempfile_helpers.py
Labels: 🚀Build

#152 Fix: 이벤트 스코어 조회 시 전체 참가자 기준으로 조회하도록 수정
  calculator/prompting.py
  events/views/views.py
Labels: 🐛 Bug, 🔨 Fix

#153 Release: 이벤트 스코어 조회 시 전체 참가자 기준으로 조회하도록 수정
  calculator/prompting.py
  events/views/views.py
Labels: 🚀Build

#154 Feat: 추첨 홀 사용자 입력 기반 신페리오 계산 및 UX 개선
  calculator/prompting.py
  calculator/serializers.py
  calculator/templates/calculator/upload_form.html
  calculator/views.py
Labels: ✨Feat

#155 feat: 신페리오 최종 점수 계산 방식을 '총 스코어'가 아닌 '총 타수'로 변경
  calculator/prompting.py
Labels: ✨Feat

#156 Release: 추첨 홀 사용자 입력 기반 신페리오 계산 방식 변경, UX 개선
  calculator/prompting.py
  calculator/serializers.py
  calculator/templates/calculator/upload_form.html
  calculator/views.py
Labels: 🚀Build

#157 hotBugTest: 참가자 스코어 기록이 부분적으로 되는 문제
  events/serializers.py
Labels: 🐛 Bug
