Repository iNESlab/Golbang_BE, pull requests merged in 2025-07, with the labels that each got.

#193 Feat: 이벤트 생성/수정/조회 시 golf club, golf course 데이터도 함께 전달/반환하도록 기능 추가
  events/migrations/0007_event_golf_club_id_event_golf_course_id.py
  events/migrations/0008_alter_event_golf_course_id.py
  events/migrations/0009_rename_golf_club_id_event_golf_club_and_more.py
  events/migrations/0010_migrate_site_to_fk.py
  events/models.py
  events/serializers.py
  events/utils.py
  events/views/views.py
Labels: ✨Feat

#195 hotfix: release,main에서 누락된 함수명 다시 덮어쓰기
  participants/stroke/redis_interface.py
Labels: 🐛 Bug

#196 hotfix: score null 허용
  participants/views/participants_view.py
Labels: 🚀Build
